language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer
    - build/cache

install:
  - composer install --prefer-dist
  - pecl install pcov || true

script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml || php vendor/bin/phpunit
  - phpenv config-rm xdebug.ini || true
  - vendor/bin/atoum -ncc -d atoum/

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
